"""Add booking status, conversation fields, form submissions

Revision ID: 59706971fa55
Revises: e5260b617da2
Create Date: 2026-02-11 15:08:36.228201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59706971fa55'
down_revision: Union[str, Sequence[str], None] = 'e5260b617da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_paused', sa.Boolean(), nullable=True))
    op.add_column('conversations', sa.Column('paused_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('last_message_is_internal', sa.Boolean(), nullable=True))
    op.add_column('form_submissions', sa.Column('booking_id', sa.Integer(), nullable=True))
    op.add_column('form_submissions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('form_submissions', sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('form_submissions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'form_submissions', 'bookings', ['booking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form_submissions', type_='foreignkey')
    op.drop_column('form_submissions', 'completed_at')
    op.drop_column('form_submissions', 'sent_at')
    op.drop_column('form_submissions', 'status')
    op.drop_column('form_submissions', 'booking_id')
    op.drop_column('conversations', 'last_message_is_internal')
    op.drop_column('conversations', 'last_message_at')
    op.drop_column('conversations', 'paused_until')
    op.drop_column('conversations', 'is_paused')
    # ### end Alembic commands ###
