"""add_lead_management_fields

Revision ID: 80cb8684db91
Revises: cc6099bd54a7
Create Date: 2026-02-13 13:20:24.792962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80cb8684db91'
down_revision: Union[str, Sequence[str], None] = 'cc6099bd54a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('status', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('source', sa.String(), nullable=True))
    op.alter_column('workspaces', 'google_token_expiry',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'google_token_expiry',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('contacts', 'source')
    op.drop_column('contacts', 'status')
    op.drop_column('contacts', 'last_name')
    op.drop_column('contacts', 'first_name')
    # ### end Alembic commands ###
