"""Add AuditLog Table

Revision ID: cc6099bd54a7
Revises: 59706971fa55
Create Date: 2026-02-12 15:13:02.470990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6099bd54a7'
down_revision: Union[str, Sequence[str], None] = '59706971fa55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('communication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_logs_id'), 'communication_logs', ['id'], unique=False)
    op.add_column('bookings', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('follow_up_sent', sa.Boolean(), nullable=True))
    op.add_column('form_submissions', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    op.add_column('inventory_items', sa.Column('last_alert_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('services', sa.Column('inventory_item_id', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('inventory_quantity_required', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'inventory_items', ['inventory_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'inventory_quantity_required')
    op.drop_column('services', 'inventory_item_id')
    op.drop_column('inventory_items', 'last_alert_at')
    op.drop_column('form_submissions', 'reminder_sent')
    op.drop_column('bookings', 'follow_up_sent')
    op.drop_column('bookings', 'reminder_sent')
    op.drop_index(op.f('ix_communication_logs_id'), table_name='communication_logs')
    op.drop_table('communication_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
